### ISSUE TITLE
Tape Dispenser/Storage?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#125]
At present the Tape situation in the Workshop is dire:
![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/dce4e8c4-4dfd-42bf-91e3-61720b11ceb8)

Yes, _I_ can always find the one I'm looking for without too much delay. 
But ... tape is the one thing people most often "borrow" from the workshop
and _other_ people can't seem to find the one they are looking for ...
so we need a better way of organising it. 💭 

_really_ like the DIY aesthetic of Tom Sachs' tape dispenser
https://www.tomsachs.com/exhibitions/voodoo

<img width="793" alt="image" src="https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/84eabe27-5d06-48d8-bbc6-24ed6bb8fe5c">

Good luck getting one for less than the price of a House! 
https://www.artnet.com/artists/tom-sachs/tape-dispenser-a-clogBHPEDaj17gyTW0cGrw2

Casey just has his tape on a rod: https://youtu.be/WHkAnVKeTvs?t=310
<img width="718" alt="image" src="https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/7ca495c8-64e5-4c42-bee6-4e442e987d48">

https://youtu.be/ESDLpxrtUUw?si=hZRtSj9nkQPlWVuc
<img width="950" alt="image" src="https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/d6b29f6f-601e-4ad7-8860-b1c020b1e8cd">

Way too many screws. But works for `Jeff` ... 👌 

I don't really want to spend _toooo_ much time on this. ⏳ 
But I want it to be tidy and ...
1. easily see all the kinds of tape we have available
2. easy to get the tape you need; ideally with a single hand
3. obvious when one roll of tape is missing (someone used it without returning it...)

**Comment by iteles** [comment]
I personally would avoid a dispenser in a workshop as the exposed piece of tape will catch all the sawdust and other particles from the workshop air and quickly become unusable and wasteful. 

I would also avoid stirring then on a rod because as you say, for our use case, the tape gets picked up and taken around the house for jobs so being stuck in the middle of a rod would be problematic. 

I would suggest that for this house's particular use case, just a box of the 'right size' Would work best - 4 sides and a back, no top. 
If you wanted to get fancy you could add a rod which could be pulled infront of the tape to hold it in place if you were to stand the box on its side (using it as a display case). It could be attached to the box with a little arm on each side that allowed some movement (but was stiff enough to hold the tape in place).

**Comment by nelsonic** [comment]
Cool. a “box” is what I was thinking too.
Specifically:

![IMG_9119](https://github.com/dwyl/workshop/assets/194400/88e53478-2b92-4b47-a8de-5e684639df44)

easily spot the tape you need. 👌
It *deliberately* “protrudes” from the shelf so that the tape is easy to see:

![IMG_9120](https://github.com/dwyl/workshop/assets/194400/b4565a5a-0b4d-40b3-9278-38dbdbc82252)

the bottom of the box is at 1.91m so above the head height for 98% of the _general_ population:

![IMG_9125](https://github.com/dwyl/workshop/assets/194400/005a626a-d909-4fbe-bfbd-bf8eac9628e2)

I’m 1.80m tall and can *easily* reach into the box to get the tape I need without any stepladder:

![IMG_9122](https://github.com/dwyl/workshop/assets/194400/2c7d7442-0118-4cff-8b9f-c5831a6c8584)

Anyone *else* that needs access can use the stepladder:

![IMG_9123](https://github.com/dwyl/workshop/assets/194400/03b7c537-a7bd-412f-a98a-3bddb792a642)

Took me just under 2h from start to finish.

![IMG_9126](https://github.com/dwyl/workshop/assets/194400/d42d08ca-7938-487d-b11a-98c569366ea7)

(gotta love that CSS overflow bug in the MVP…)

2h is *Definitely* not worth my time in terms of my hourly rate … 💸
 but I’m glad I made something that sets the *tone* for keeping the tape tidy.

@iteles please test + feedback when you get a chance. Thanks. 🙏

**Comment by nelsonic** [comment]
This was my project research, ideation and cutting list page for this: 📓 

![image](https://github.com/dwyl/workshop/assets/194400/9370a3d5-9486-430c-97cf-64e7600da260)

Not much to go on ... but you can see that I measured all the tape we have 📏 
and gave a 20mm margin for future bigger tape. 👌

**Comment by nelsonic** [comment]
Inês recently found some packing tape in the box. Guessing she just didn’t see the request for feedback. Anyway, I’m calling this done. ✅
