### ISSUE TITLE
Sell Spare Cement Mixer?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#144]
recently our cement mixer died on a concrete “pour” day. So rather than waiting for it to be fixed - and wasting the day - I made the decision to buy a new one. 
it cost €275 and wasting the day would have cost €130 in direct labor and €300 in opportunity cost. 

Meanwhile we got the “old” one fixed for €65 (it was just the button that needed to be replaced).
But that means we now have two: 

![IMG_5709](https://github.com/dwyl/workshop/assets/194400/7eafe690-9349-4296-ac59-39ea425f4901)

So we need to sell or store the other one. 💭

**Comment by nelsonic** [comment]
We can easily sell it on OLX for €200 (yes, a small loss, but not in terms of making progress on the project …)
Or we could store it (covered) at Landim until our “old” one dies again … ⏳

**Comment by iteles** [comment]
Pinheiro doesn't know anyone who needs a cement mixer.

Please let me know which one is the one we're selling and I'll list it on OLX.

**Comment by nelsonic** [comment]
The newer looking one is the one to sell. Other than a few scratches/scrapes from use, they are both identical.

**Comment by nelsonic** [comment]
@iteles you have agreed with your Aunt that Landim will have the Cement Mixer; but not updated this issue ...
The mixer will be taken to Landim when we next collect the auger.

**Comment by iteles** [comment]
Indeed, I am behind on updates!

**Comment by nelsonic** [comment]
`Landim` paid `€200` for it. They got a good deal. Hope they put it to good use. 👌
