### ISSUE TITLE
BUG: Find Lost iPhone! 📱 🤷 🔍 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#145]
Need a contraption to help us find the lost iPhone ... 💭

**Comment by nelsonic** [comment]
The idea that came to me in my sleep last night was to mount several strong magnets 🧲 to a broom and drag it along in the hope of picking up the iPhone because of the MagSafe. But when I tested it in the workshop, the extra strong neodymium magnets had to be aligned *perfectly* with the MagSafe … and if the phone is right-side-up I.e. screen up, the Magnets are useless at picking up the phone. 

I immediately thought: Metal Detector!!

**Comment by nelsonic** [comment]
No seller in Braga had an Metal Detector in stock so I made a make-shift one:

![IMG_6526](https://github.com/dwyl/workshop/assets/194400/61e3cd39-485e-4b45-9a8c-b7fcf85761d9)
![IMG_6525](https://github.com/dwyl/workshop/assets/194400/f2a4a856-b8b9-4887-9fb1-dfa335406ebc)

it works well:

![IMG_6533](https://github.com/dwyl/workshop/assets/194400/eaf6b4f1-691f-428b-a49a-f6a4061e373f)

**Comment by nelsonic** [comment]
I spotted the case immediately on the side of the road:

![IMG_6527](https://github.com/dwyl/workshop/assets/194400/a048c5b2-08e2-4d81-af48-b1bb3826ca18)

But sadly, the iPhone had been dislodged and projected from it. 😢

searched the area with the ***iPhone finder 9000*** for around an hour then checked **FindMy** again… it had updated the last known location!! 🎉

**Comment by nelsonic** [comment]
Using the FindMy location, 

![IMG_6537](https://github.com/dwyl/workshop/assets/194400/9b41f40a-bdb4-43c5-a737-76ca9e39d412)

we spoke to as many local businesses in the area as we could find.
And eventually the Butcher informed us that a lady had mentioned she found a phone yesterday!
the butcher knew exactly where the lady lived and took us to her!!

![IMG_6545](https://github.com/dwyl/workshop/assets/194400/055e0bd0-fffd-4faa-9a68-6b02475be358)

The lady did in fact have it and handed it over to @iteles 
![IMG_6547](https://github.com/dwyl/workshop/assets/194400/76e615a5-c486-4775-adf5-b97fd2bdcddf)

**Comment by nelsonic** [comment]
The phone is in bad shape, but still recoverable!
Rear 3x Zoom Camera lens smashed:

![IMG_6573](https://github.com/dwyl/workshop/assets/194400/dc4275a9-d8de-4ab5-8022-a3ae0632340a)

rear glass cracked:
![IMG_6574](https://github.com/dwyl/workshop/assets/194400/0d0b3a7d-d933-42f0-a020-2b4879bd9fd0)

Front screen saved by the tempered glass screen protector:

![IMG_6575](https://github.com/dwyl/workshop/assets/194400/d8187e91-6648-41ba-83e0-83c31be047d9)

Replacing the 3X Zoom Camera Lens (€30) and a new - stronger - case (€20) that will totally hide the cracked rear glass and a new screen protector (€5) will bring this €900 iPhone back to life. 

So glad we found it. 🎉

**Comment by iteles** [comment]
This is amazing and woah. Thank you for coming with me to look for it!

**Comment by nelsonic** [comment]
@iteles yeah, for the price of an `iPhone 13 Pro 1Tb` ... I can afford to take the morning off to hut for it. 💰 🙃
Again, stoked we found it and you were able to get the lens replaced.
Have you ordered a new sturdier magsafe case on `Black Friday`?

**Comment by iteles** [comment]
I checked and there was nothing on black friday so then I forgot 🤦‍♀️ 
I added one to the Shoshin amazon cart for whenever we check out there again.

**Comment by nelsonic** [comment]
@iteles while this _looks_ good in theory, it has zero reviews ...

https://www.amazon.es/-/pt/gp/product/B0BG2SZ9PD
<img width="1085" alt="image" src="https://github.com/dwyl/workshop/assets/194400/5cc7398b-f088-4f33-b141-9b9644d5916f">

Obviously the Canary Yellow `#FFFF8F` is more your pref ...

I included one of these: https://www.amazon.es/gp/product/B0B2LVZ4WM in the `CyberMonday` order yesterday:
<img width="1051" alt="image" src="https://github.com/dwyl/workshop/assets/194400/9a219b01-1aa5-4597-826e-70a3c10dc350">

It has _many_ 5-star reviews and is basically the same as the case I'm using; very sturdy/protective. ⭐ 
I wasn't _sure_ about the color ("bronze") ... So happy to cancel it and get this one you're suggesting instead. 💭

**Comment by iteles** [comment]
I would have probably preferred any other colour (except purple) 😂 But it might be nice in person. 
I'll return it if it's not and get the yellow one, which I also like because it's not transparent and the back of the phone is pretty cracked too (I also don't like flashing the note that I like to keep in the back of my phone) 👌
