### ISSUE TITLE
Build Second Baby Camera Mount

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#162]
We’re blessed to have _two_ children. ✌️
So @iteles bought a babysense *dual* camera monitor.
But since we only had one mount the second camera has been offline for a ***while*** … 🙃

# Todo

- [x] build a second camera mount similar to the original so we can *use* the second camera.

**Comment by nelsonic** [comment]
second mount made in workshop based on *working* design of the first one:

![IMG_5309](https://github.com/dwyl/workshop/assets/194400/de492ee3-ef16-47cd-a9ee-8bf745d8b771)

**Comment by nelsonic** [comment]
Mounted in place on windowsill:

![IMG_5310](https://github.com/dwyl/workshop/assets/194400/25920eae-d430-4aa6-8e98-4f4483e7a783)

**Comment by nelsonic** [comment]
Confirmed both cameras operating and pointing at their respective beds: 🛏️ 

![IMG_5311](https://github.com/dwyl/workshop/assets/194400/33f328d3-86f7-4626-a33b-4e3a8fc01357)


![IMG_5312](https://github.com/dwyl/workshop/assets/194400/8a2a87bc-f0ad-4e96-ae1e-daf9480f07a0)

@iteles over to you for review.

**Comment by nelsonic** [comment]
Along the way, also ordered a new (EU 🔌) AC Adapter to power the second babysense camera as it had gone missing:

https://amzn.eu/d/cgK0ObT
![IMG_5314](https://github.com/dwyl/workshop/assets/194400/1f34fa24-f701-45d1-81d9-661ae2db74f6)

![IMG_5313](https://github.com/dwyl/workshop/assets/194400/94ec5565-2019-42d4-a5b5-2c3359abeea5)

So had to spend a _little_ money to solve the problem. 💸🙃

**Comment by iteles** [comment]
Working great, thanks!

**Comment by asntc** [comment]
Thanks @nelsonic 👌 
https://youtu.be/7YvAYIJSSZY 😜

**Comment by nelsonic** [comment]
Cool. Closing. ✅
