### ISSUE TITLE
Chore: Replace Tesla Model 3 Air Filter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#163]
# ⚠️Warning: Contains First World Problems! ⚠️

## Context

We wanted an electric car to pair with our solar panels https://github.com/dwyl/home/issues/20 and there wasn’t much choice in terms of range/quality when we were looking in 2020 … you have to remember, this was peak COVID supply chain shortage and Volvo hadn’t released any of their Electric Models …
We ended up buying a **_used_** Tesla Model 3 RWD LFP from Germany 🇩🇪 for *muuuch* (37%!) cheaper than the sticker price in PT and paid a local company to import & legalise it for us. We *eventually* received it in Feb 2021. ⏳

## 3 years Later 

the time has passed, we’ve driven it 37 _thousand_ Kms in that time and the cabin air filter is _spent_!

Sadly, the cabin air filter being saturated with dirt means that being in a traffic jam with stinky diesel ⛽️ cars, the fumes enter the cabin and we are forced to turn off the aircon completely! #FirstWorldProblems 🙃

# Todo

- [x] follow instructions to replace filter: https://youtu.be/PJ9-SODKk14

We’ve had the replacement filter for a few weeks, but I’ve procrastinated on this cause I don’t drive the car very often… but @iteles drives it every day to take our son to school. 🌳 so they are both affected by the fumes. 😢
Going to see if I can get this done *now*. ⏳🤞🏼🧑‍🔧

**Comment by nelsonic** [comment]
This was a total nightmare.
Having to remove two trim panels is insane! 

![IMG_5396](https://github.com/dwyl/workshop/assets/194400/5ca8e9a3-df50-4e54-aced-3f9c48c3e4e7)

I ended up watching 5 instructional videoed but the videos on YT were all for the more recent 2022< model 3 or the older <2020 (pre heat pump) Model 3 so the screw was in a different place from the videos. 🤦‍♂️

The torx screw was in such an awkward place that ended up needing to use a right angle screwdriver bit holder:

![IMG_5397](https://github.com/dwyl/workshop/assets/194400/a39559d0-87ae-4265-af1e-7168778a4612)
![IMG_5398](https://github.com/dwyl/workshop/assets/194400/e9005f9e-ead2-4f8f-8210-93d917bec8a1)

eventually liberating the old filters:

![IMG_5400](https://github.com/dwyl/workshop/assets/194400/34c7ccc3-2e43-46df-9144-1eeb7cbdb779)
![IMG_5401](https://github.com/dwyl/workshop/assets/194400/72fe6fd6-1744-4d05-9b98-ffaf227b161d)
![IMG_5404](https://github.com/dwyl/workshop/assets/194400/45965399-1a16-49e4-9955-0fdd26e94f50)
![IMG_5405](https://github.com/dwyl/workshop/assets/194400/ef1a943d-37d0-4c66-be07-387c1e1eb259)
![IMG_5406](https://github.com/dwyl/workshop/assets/194400/1c0b9aa4-f646-416a-8aa8-ba494d0dc233)

put the new ones in as per instructions, filter membrane forward and activated charcoal back:

![IMG_5408](https://github.com/dwyl/workshop/assets/194400/d669c286-b579-462f-b7f2-2d951cab1465)
![IMG_5409](https://github.com/dwyl/workshop/assets/194400/918c5549-5a95-40c3-bfc7-5b4965c2d1e1)

replaced the trim panels:

![IMG_5410](https://github.com/dwyl/workshop/assets/194400/ce43d556-dea4-4821-9208-e1a704054264)

overall a *horrible* experience. I *definitely* don’t look forward to doing again. 😢
Though, obviously *second* time round I’d do it *muuuuuch* faster. 🙃

**Comment by nelsonic** [comment]
@iteles please use the AirCon on your drive this morning and confirm everything is working as expected and you aren’t getting any stinky diesel fumes. 🙏🤞🏼

**Comment by iteles** [comment]
I have not felt any fumes , these seem to be working 👌🏻

**Comment by nelsonic** [comment]
The real test will be stuck in a traffic jam behind a diesel truck … 🛻

**Comment by nelsonic** [comment]
This was a truly horrible task that Tesla could have made _much_ simpler if they wanted. ⏳ 
If the Tesla service centre price per hour (labor cost) wasn't so high, I'd get them to replace it next time. 💭 
Hopefully won't have to do this again for another year. 🙃 
Closing. ✅
