### ISSUE TITLE
Feat: Sandpaper Storage/Organiser

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#164]
I've reached the point of this _bugging_ me. 🐛 
Our _manual_ sandpaper sheets have been sitting on a _shelf_ of the workshop for the past couple of years.
This is "OK" if I'm the only one using them because I just replace them where I got them from after use ...
But with _other_ people using the workshop space and sandpaper, it quickly descends into chaos.
Because not having the "right" place to put the sheets means people leave them _anywhere_ ... 😢 

We currently have 4 grits:

![image](https://github.com/dwyl/workshop/assets/194400/66617ebc-14aa-47d6-8541-1e897e85921d)

- [x] 80
- [x] 120
- [x] 150
- [x] 320
- [x] 600

My plan is to _build_ a custom sandpaper organiser and wall mount it near the _electric_ sanders (near the exterior door).
I expect this to take me `T1h` ... ⌛

**Comment by nelsonic** [comment]
The sandpaper is sold by the sheet or in packs at our local hardware store:
https://www.leroymerlin.pt/produtos/ferramentas/ferramentas-de-mao/lixas-e-esponjas/lixa-manual-dexter-madeira-gr320-62266141.html
![image](https://github.com/dwyl/workshop/assets/194400/78c8e07e-eca6-4599-a160-bba19b2a0594)

**Comment by nelsonic** [comment]
Assembled and glue is drying:

![IMG_6911](https://github.com/dwyl/workshop/assets/194400/02712fff-d5e1-419b-bcdc-6f04a6951dd7)

will wall-mount it later today; holes already drilled. 👌

**Comment by iteles** [comment]
4 grits! This is a Montessori classroom dream 😆

**Comment by nelsonic** [comment]
Wall mounted with the ***FIVE*** grits of sandpaper. ✅

![IMG_6954](https://github.com/dwyl/workshop/assets/194400/04b392e7-bb0b-4bd7-9de3-b7009a2b7e2d)

p.s. our Montessori PlayGroup https://github.com/bmhco/shared/issues/7#issuecomment-1446520135 is *very* welcome to use as much of the sandpaper as they need! 👌

**Comment by nelsonic** [comment]
Gradually organising the workshop into somewhere *anyone* can immediately find what they need for creative projects. ⏳🤞🏼
