### ISSUE TITLE
Chore: Buy Paper Clips! 🔗 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#92]
I keep having to search for paper clips around the house and I _really_ don't want to be wasting my time!
Want to have a stock of at least 2 [standard] sizes of paperclip in the workshop / craft room at all times for "Bricolage" 

https://www.staples.pt/pt/pt/staples-clipes-de-papel-n-4-32-mm-aco-galvanizado-prateado-embalagem-de-400-unidades-704834#notify
![image](https://user-images.githubusercontent.com/194400/208246908-bda32e47-531e-45ad-9c86-491b6fd6b379.png)

The fact that these cannot be bought online is the reason Staples will eventually go out-of-biz and Amazon will eat their lunch!

[https://www.amazon.es/stores/page/46719109-3317-4087-9DD6-3B37453A1BE7/search?terms=clipes%20de%20papel](https://www.amazon.es/stores/page/46719109-3317-4087-9DD6-3B37453A1BE7/search?ref_=ast_dp_bln_nofrnas_sto&store_ref=bl_ast_dp_nofrnas_sto&terms=clipes%20de%20papel)
![image](https://user-images.githubusercontent.com/194400/208247175-9110bb11-f4c1-44bb-bbfd-7a7b5c167a19.png)

https://www.amazon.es/APLI-11715-Clips-galvanizados-clips/dp/B009D02PFG
![image](https://user-images.githubusercontent.com/194400/208247284-5d73d3da-a9cd-4480-8530-270ded50d6eb.png)

As much as I want to support a "local" (multinational!) IRL box store so that it stays open, this is _cheaper_ and available next-day.

**Comment by iteles** [comment]
I have a bunch, didn't know you needed them! I haven't used them in years!

I'll put a box on your desk tonight.

**Comment by nelsonic** [comment]
@iteles I’m quite keen to have a standard size and either galvanised or stainless steel cause I intend to use them in the workshop. But if you have paper clips that you aren’t using, please share. 🙏

**Comment by nelsonic** [comment]
![Uploading IMG_0025.jpeg…]()

done. ✅

**Comment by nelsonic** [comment]
![IMG_0025](https://github.com/dwyl/workshop/assets/194400/24ed6416-2e6f-460d-a16e-d4637160bcc8)
